version: '3.1'
services:
  stats-server:
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explore_with_me
      - SPRING_DATASOURCE_USER=explore_with_me
      - SPRING_DATASOURCE_PASSWORD=explore

  stats-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=explore_with_me
      - POSTGRES_PASSWORD=explore
      - DB_HOST=db
      - DB_PORT=5432

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
